//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resources
    {
        public int Id { get; set; }
        public string Price { get; set; }
        public int Id_Repair_reauest { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
    
        public virtual Repair_request Repair_request { get; set; }
    }
}
